### ISSUE TITLE
queryLogic: 'module' object has no attribute 'choise'

### ISSUE THREAD

**Issue by PavelTrutman** [brmson/Personal-Assistant#10]
``` python
Traceback (most recent call last):
  File "/root/Personal-Assistant/modules/querylogic/query_control.py", line 128, in <module>
    qc.listen()
  File "/root/Personal-Assistant/modules/querylogic/query_control.py", line 108, in listen
    replyData = self.application(data)
  File "/root/Personal-Assistant/modules/querylogic/query_control.py", line 74, in application
    return {'answer': random.choise(message)}
AttributeError: 'module' object has no attribute 'choise'
```

**Comment by drapejak** [comment]
i'm going to check it

**Comment by drapejak** [comment]
I think it would be ok
