### ISSUE TITLE
tell me a joke bug

### ISSUE THREAD

**Issue by PavelTrutman** [brmson/Personal-Assistant#11]
Query logic module returns None instead of string with an answer when "Tell me a joke." asked.

**Comment by drapejak** [comment]
I'm going to check it

**Comment by drapejak** [comment]
I think it would be ok

**Comment by PavelTrutman** [comment]
It is not better now.

``` python
Traceback (most recent call last):
  File "/root/Personal-Assistant/modules/querylogic/query_control.py", line 128, in <module>
    qc.listen()
  File "/root/Personal-Assistant/modules/querylogic/query_control.py", line 108, in listen
    replyData = self.application(data)
  File "/root/Personal-Assistant/modules/querylogic/query_control.py", line 77, in application
    answer=module.query_resolution(intent, parsedQuery, self.config)
  File "/root/Personal-Assistant/modules/querylogic/modules/accessories.py", line 62, in query_resolution
    return self.call_switcher(query)
  File "/root/Personal-Assistant/modules/querylogic/modules/accessories.py", line 58, in call_switcher
    return Accessories.switcher[key](self,query)
TypeError: unhashable type: 'list'
```

**Comment by drapejak** [comment]
solved
