### ISSUE TITLE
Problem with geopy library

### ISSUE THREAD

**Issue by drapejak** [brmson/Personal-Assistant#8]
Problem had found with geopy library. Have you same problem as me in virtual machine? I've tried to solve it but without any good result.

my error:
page = requester(req, timeout=(timeout or self.timeout), *_kwargs)
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(_args)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ql_offline_test.py", line 31, in <module>
    initModule=module.init_hook()
  File "/home/kubin/Plocha/GitFolder/Personal-Assistant/modules/querylogic/modules/weather.py", line 24, in init_hook
    homelocation=getLocation(location);
  File "/home/kubin/Plocha/GitFolder/Personal-Assistant/modules/querylogic/modules/weather.py", line 17, in getLocation
    location = geolocator.geocode(place)
  File "/usr/local/lib/python3.4/dist-packages/geopy/geocoders/osm.py", line 193, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/usr/local/lib/python3.4/dist-packages/geopy/geocoders/base.py", line 158, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderInsufficientPrivileges: HTTP Error 403: Forbidden

**Comment by PavelTrutman** [comment]
It is working for me without any error. It looks like you can not open some webpage.

**Comment by drapejak** [comment]
ok
